name: Daily DSA Problem Commit

on:
  schedule:
    - cron: "30 4 * * *"  # Daily at 4:30 AM UTC
  workflow_dispatch:

jobs:
  add-dsa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new DSA file with dummy solution
        run: |
          mkdir -p DSA
          TODAY=$(date -u +"%Y_%m_%d")
          FILE="DSA/DSA_$TODAY.cs"
          echo "// DSA Problem for $TODAY" > $FILE
          echo "// Sample: Reverse an Array" >> $FILE
          cat << EOF >> $FILE

using System;

class Solution {
    public static void ReverseArray(int[] arr) {
        int left = 0, right = arr.Length - 1;
        while (left < right) {
            int temp = arr[left];
            arr[left] = arr[right];
            arr[right] = temp;
            left++;
            right--;
        }
    }

    public static void Main() {
        int[] nums = {1, 2, 3, 4, 5};
        ReverseArray(nums);
        Console.WriteLine(string.Join(", ", nums));
    }
}
EOF

      - name: Configure git
        run: |
          git config user.name "savya"
          git config user.email "savyasachi.thati@gmail.com"

      - name: Commit and push
        run: |
          git add DSA/
          git commit -m "Add daily DSA solution for $(date -u +"%Y-%m-%d")" || echo "Nothing to commit"
          git push
