name: Daily Commit
on:
  schedule:
    - cron: "17 3 * * *"  # Day 1: 3:17 AM UTC
    - cron: "42 6 * * *"  # Day 2: 6:42 AM UTC
    - cron: "59 1 * * *"  # Day 3: 1:59 AM UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Last updated: $(date -u)" > activity.txt

      - name: Configure Git
        run: |
          git config user.name "savya"
          git config user.email "savyasachi.thati@gmail.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "commit: $(date -u)" || echo "No changes to commit"
          git push

